# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3089850a775db9fd7993686de183c28603b938a7bead794414da1bad002990379777ef59e0aa5387a2930ca718af0bd5cd94cba419310543ad79713144dd943e

test:
  secret_key_base: 378f49927c1896c997c4b5659c144280ada479971c61054d44f7fcb76ce0bd485c86eccbb95ba59383e317a4319a684f8644e7ea24a213535265e6a223be79f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
